project test infrastructure and github actions for testing and showing documentation (#4)
* renaming to LibCore

* test suite seems ready

* workflow code test github action

* fixes for style and workflow:
* eliminate duplicate pull request workflow,
as it already runs on push
* set working-directory for the test

* try 2:
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/uu-afp-2021-team-proj-abbr/uu-afp-2021-team-proj-abbr/backend/team-proj-abbr'. No such file or directory

* try 3

* try 4

* looks like its working, cleaning up
hopefully this works too

* maybe this fixes it
allow insecure commands working directory .

* first try gh pages

* try 2 gh-pages

* try 3 gh-pages
we got an empty deploy but it's almost working
it's only a matter of finding the right dist folder

* trying to add to a subdir
to support multiple github pages
and also cleanup with env variable

* it works, but try 2 for env vars

* it didn't run for some reason!

* this should fail

* this should not fail

* let'see now, only applied to one
useless for now

* env doesn't seem to work
the workflow doesn't run
trying with strategy

* what is this

* this is madness

* dmitri comments